import type { Color, ColorOption } from '@/types/country';

export const COLOR_PALETTE: ColorOption[] = [
  {
    id: 'red',
    hex: '#FF0000',
    name: {
      en: 'Red',
      ja: '赤',
      zh: '红色',
      fr: 'Rouge',
      es: 'Rojo',
      pt: 'Vermelho',
      ar: 'أحمر',
      th: 'แดง',
      vi: 'Đỏ',
      id: 'Merah',
      ru: 'Красный',
    },
  },
  {
    id: 'blue',
    hex: '#0000FF',
    name: {
      en: 'Blue',
      ja: '青',
      zh: '蓝色',
      fr: 'Bleu',
      es: 'Azul',
      pt: 'Azul',
      ar: 'أزرق',
      th: 'น้ำเงิน',
      vi: 'Xanh dương',
      id: 'Biru',
      ru: 'Синий',
    },
  },
  {
    id: 'white',
    hex: '#FFFFFF',
    name: {
      en: 'White',
      ja: '白',
      zh: '白色',
      fr: 'Blanc',
      es: 'Blanco',
      pt: 'Branco',
      ar: 'أبيض',
      th: 'ขาว',
      vi: 'Trắng',
      id: 'Putih',
      ru: 'Белый',
    },
  },
  {
    id: 'green',
    hex: '#00FF00',
    name: {
      en: 'Green',
      ja: '緑',
      zh: '绿色',
      fr: 'Vert',
      es: 'Verde',
      pt: 'Verde',
      ar: 'أخضر',
      th: 'เขียว',
      vi: 'Xanh lá',
      id: 'Hijau',
      ru: 'Зелёный',
    },
  },
  {
    id: 'yellow',
    hex: '#FFFF00',
    name: {
      en: 'Yellow',
      ja: '黄',
      zh: '黄色',
      fr: 'Jaune',
      es: 'Amarillo',
      pt: 'Amarelo',
      ar: 'أصفر',
      th: 'เหลือง',
      vi: 'Vàng',
      id: 'Kuning',
      ru: 'Жёлтый',
    },
  },
  {
    id: 'black',
    hex: '#000000',
    name: {
      en: 'Black',
      ja: '黒',
      zh: '黑色',
      fr: 'Noir',
      es: 'Negro',
      pt: 'Preto',
      ar: 'أسود',
      th: 'ดำ',
      vi: 'Đen',
      id: 'Hitam',
      ru: 'Чёрный',
    },
  },
  {
    id: 'orange',
    hex: '#FFA500',
    name: {
      en: 'Orange',
      ja: 'オレンジ',
      zh: '橙色',
      fr: 'Orange',
      es: 'Naranja',
      pt: 'Laranja',
      ar: 'برتقالي',
      th: 'ส้ม',
      vi: 'Cam',
      id: 'Oranye',
      ru: 'Оранжевый',
    },
  },
  {
    id: 'purple',
    hex: '#800080',
    name: {
      en: 'Purple',
      ja: '紫',
      zh: '紫色',
      fr: 'Violet',
      es: 'Morado',
      pt: 'Roxo',
      ar: 'بنفسجي',
      th: 'ม่วง',
      vi: 'Tím',
      id: 'Ungu',
      ru: 'Фиолетовый',
    },
  },
];

export function getColorHex(colorId: Color): string {
  const color = COLOR_PALETTE.find((c) => c.id === colorId);
  return color?.hex || '#CCCCCC';
}
