import type { SymbolOption } from '@/types/country';

export const SYMBOL_OPTIONS: SymbolOption[] = [
  {
    id: 'star',
    icon: '⭐',
    name: {
      en: 'Star',
      ja: '星',
      zh: '星星',
      fr: 'Étoile',
      es: 'Estrella',
      pt: 'Estrela',
      ar: 'نجمة',
      th: 'ดาว',
      vi: 'Ngôi sao',
      id: 'Bintang',
      ru: 'Звезда',
    },
  },
  {
    id: 'moon',
    icon: '🌙',
    name: {
      en: 'Moon',
      ja: '月',
      zh: '月亮',
      fr: 'Lune',
      es: 'Luna',
      pt: 'Lua',
      ar: 'قمر',
      th: 'ดวงจันทร์',
      vi: 'Mặt trăng',
      id: 'Bulan',
      ru: 'Луна',
    },
  },
  {
    id: 'cross',
    icon: '✚',
    name: {
      en: 'Cross',
      ja: '十字',
      zh: '十字',
      fr: 'Croix',
      es: 'Cruz',
      pt: 'Cruz',
      ar: 'صليب',
      th: 'กางเขน',
      vi: 'Thập tự',
      id: 'Salib',
      ru: 'Крест',
    },
  },
  {
    id: 'circle',
    icon: '⭕',
    name: {
      en: 'Circle',
      ja: '円',
      zh: '圆形',
      fr: 'Cercle',
      es: 'Círculo',
      pt: 'Círculo',
      ar: 'دائرة',
      th: 'วงกลม',
      vi: 'Vòng tròn',
      id: 'Lingkaran',
      ru: 'Круг',
    },
  },
  {
    id: 'triangle',
    icon: '🔺',
    name: {
      en: 'Triangle',
      ja: '三角形',
      zh: '三角形',
      fr: 'Triangle',
      es: 'Triángulo',
      pt: 'Triângulo',
      ar: 'مثلث',
      th: 'สามเหลี่ยม',
      vi: 'Tam giác',
      id: 'Segitiga',
      ru: 'Треугольник',
    },
  },
  {
    id: 'emblem',
    icon: '🛡️',
    name: {
      en: 'Emblem',
      ja: '紋章',
      zh: '徽章',
      fr: 'Emblème',
      es: 'Emblema',
      pt: 'Emblema',
      ar: 'شعار',
      th: 'ตราสัญลักษณ์',
      vi: 'Huy hiệu',
      id: 'Lambang',
      ru: 'Эмблема',
    },
  },
  {
    id: 'animal',
    icon: '🦅',
    name: {
      en: 'Animal',
      ja: '動物',
      zh: '动物',
      fr: 'Animal',
      es: 'Animal',
      pt: 'Animal',
      ar: 'حيوان',
      th: 'สัตว์',
      vi: 'Động vật',
      id: 'Hewan',
      ru: 'Животное',
    },
  },
  {
    id: 'plant',
    icon: '🍁',
    name: {
      en: 'Plant',
      ja: '植物',
      zh: '植物',
      fr: 'Plante',
      es: 'Planta',
      pt: 'Planta',
      ar: 'نبات',
      th: 'พืช',
      vi: 'Thực vật',
      id: 'Tumbuhan',
      ru: 'Растение',
    },
  },
];
